[Unit]
Requires=ethercat.service
BindsTo=ethercat.service
After=ethercat.service

[Service]
LimitMEMLOCK=infinity
LimitRTPRIO=80
CPUSchedulingPolicy=fifo
CPUSchedulingPriority=70
CPUSchedulingResetOnFork=true
